- name: deploy nkp management cluster
  hosts: bootstrap
  vars_files:
    - ../vars/all.yaml
    - ../vars/custom_resources.yaml

  tasks:
    
    - name: download nkp air-gapped bundle
      get_url:
        url: "{{ NKP_AIRGAPPED_BUNDER_URL }}"
        dest: "/root/nkp-air-gapped-bundle_v2.14.0_linux_amd64.tar.gz"
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 10
    
    #    - name: Copy nkp air-gapped bundle to remote
    #      shell: rsync -chavz {{ NKP_AIRGAPPED_BUNDLE_PATH }}  {{ HARBOR_IP }}:/root/

    - name: extract nkp bundle
      unarchive:
        src: "/root/nkp-air-gapped-bundle_v2.14.0_linux_amd64.tar.gz"
        dest: "/root/nkp"
        remote_src: yes
        creates: "/root/nkp/nkp-v2.14.0"

    - name: copy nkp cli and to /usr/local/bin/
      copy:
        src: "/root/nkp/nkp-v2.14.0/cli/nkp"
        dest: "/usr/local/bin/nkp"
        mode: '0755'
        remote_src: yes

    - name: copy kubectl to /usr/local/bin/
      copy:
        src: "/root/nkp/nkp-v2.14.0/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'
        remote_src: yes

    - name: set environment variables
      shell: |
        /usr/bin/echo "export NUTANIX_USER={{ NUTANIX_USER }}" >> /root/.bashrc
        /usr/bin/echo "export NUTANIX_PASSWORD={{ NUTANIX_PASSWORD }}" >> /root/.bashrc
        source /root/.bashrc    
        #    - name: source environment immediately
        #      shell: source /root/.bashrc
        #      args:
        #        executable: /bin/bash

    - name: docker login to harbor registry
      shell: docker login https://{{ HARBOR_IP }}/nkp -u {{ HARBOR_USER }} -p {{ HARBOR_PASSWORD }}

    - name: push image bundles to registry
      shell: |
        /usr/local/bin/nkp push bundle --bundle {{ item }} --to-registry=https://{{ HARBOR_IP }}/nkp --to-registry-ca-cert-file=/root/nkp/reg-certs/ca.crt --to-registry-username={{ HARBOR_USER }} --to-registry-password={{ HARBOR_PASSWORD }}
      args:
        chdir: "/root/nkp/nkp-v2.14.0/container-images"
      loop:
        - "kommander-image-bundle-v2.14.0.tar"
        - "konvoy-image-bundle-v2.14.0.tar"
        - "nkp-catalog-applications-image-bundle-v2.14.0.tar"

    - name: load bootstrap images
      shell: docker load -i {{ item }}
      args:
        chdir: "/root/nkp/nkp-v2.14.0"
      loop:
        - "konvoy-bootstrap-image-v2.14.0.tar"
        - "nkp-image-builder-image-v0.22.3.tar"

          #    - name: set custom conf
          #      set_fact:
          #        CONTROL_PLANE_REPLICAS: "3"
          #        CONTROL_PLANE_DISK_SIZE: "80"
          #        CONTROL_PLANE_MEMORY: "16"
          #        CONTROL_PLANE_VCPUS: "4"
          #        WORKER_REPLICAS: "4"
          #        WORKER_DISK_SIZE: "80"
          #        WORKER_MEMORY: "32"
          #        WORKER_VCPUS: "8"
          #        KUBERNETES_POD_NETWORK_CIDR: "192.168.0.0/16"
          #        KUBERNETES_SERVICE_CIDR: "10.96.0.0/12"
          #      when: CHANGE == "false"

    - name: create management cluster with default conf 
      shell: |
        /usr/local/bin/nkp create cluster nutanix \
        --cluster-name={{ MGMT_CLUSTER_NAME }} \
        --control-plane-prism-element-cluster={{ PE_CLUSTER_NAME }} \
        --control-plane-subnets={{ SUBNET }} \
        --control-plane-endpoint-ip={{ MGMT_CP_ENDPOINT }} \
        --control-plane-vm-image={{ NKP_VMS_IMAGE }} \
        --worker-prism-element-cluster={{ PE_CLUSTER_NAME }} \
        --worker-subnets={{ SUBNET }} \
        --worker-vm-image={{ NKP_VMS_IMAGE }} \
        --csi-storage-container={{ STORAGE_CONTAINER }} \
        --kubernetes-service-load-balancer-ip-range={{ MGMT_LB_IP_RANGE }} \
        --endpoint="https://{{ PC_ENDPOINT }}:9440" \
        --insecure=true \
        --ssh-public-key-file=/root/.ssh/id_rsa.pub \
        --registry-url=https://{{ HARBOR_IP }} \
        --registry-cacert=/root/nkp/reg-certs/ca.crt \
        --registry-mirror-url=https://{{ HARBOR_IP }}/nkp \
        --registry-mirror-cacert=/root/nkp/reg-certs/ca.crt \
        --registry-mirror-password={{ HARBOR_PASSWORD }} \
        --registry-mirror-username={{ HARBOR_USER }} \
        --airgapped \
        --self-managed
      args:
        chdir: "/root/nkp/nkp-v2.14.0"
      when: CHANGE == "false"
        
    - name: create management cluster with custom conf
      shell: |
        /usr/local/bin/nkp create cluster nutanix \
        --cluster-name={{ MGMT_CLUSTER_NAME }} \
        --control-plane-prism-element-cluster={{ PE_CLUSTER_NAME }} \
        --control-plane-subnets={{ SUBNET }} \
        --control-plane-endpoint-ip={{ MGMT_CP_ENDPOINT }} \
        --control-plane-vm-image={{ NKP_VMS_IMAGE }} \
        --control-plane-disk-size={{ CONTROL_PLANE_DISK_SIZE }} \
        --control-plane-memory={{ CONTROL_PLANE_MEMORY }} \
        --control-plane-vcpus={{ CONTROL_PLANE_VCPUS }} \
        --control-plane-replicas={{ CONTROL_PLANE_REPLICAS }} \
        --worker-prism-element-cluster={{ PE_CLUSTER_NAME }} \
        --worker-subnets={{ SUBNET }} \
        --worker-vm-image={{ NKP_VMS_IMAGE }} \
        --worker-disk-size={{ WORKER_DISK_SIZE }} \
        --worker-memory={{ WORKER_MEMORY }} \
        --worker-vcpus={{ WORKER_VCPUS }} \
        --worker-replicas={{ WORKER_REPLICAS }} \
        --csi-storage-container={{ STORAGE_CONTAINER }} \
        --kubernetes-service-load-balancer-ip-range={{ MGMT_LB_IP_RANGE }} \
        --kubernetes-pod-network-cidr={{ KUBERNETES_POD_NETWORK_CIDR }} \
        --kubernetes-service-cidr={{ KUBERNETES_SERVICE_CIDR }} \
        --endpoint="https://{{ PC_ENDPOINT }}:9440" \
        --insecure=true \
        --ssh-public-key-file=/root/.ssh/id_rsa.pub \
        --registry-url=https://{{ HARBOR_IP }} \
        --registry-cacert=/root/nkp/reg-certs/ca.crt \
        --registry-mirror-url=https://{{ HARBOR_IP }}/nkp \
        --registry-mirror-cacert=/root/nkp/reg-certs/ca.crt \
        --registry-mirror-password={{ HARBOR_PASSWORD }} \
        --registry-mirror-username={{ HARBOR_USER }} \
        --airgapped \
        --self-managed
      args:
        chdir: "/root/nkp/nkp-v2.14.0"    
      when: CHANGE == "true"


    - shell: /usr/local/bin/nkp get dashboard --kubeconfig /root/nkp/nkp-v2.14.0/{{ MGMT_CLUSTER_NAME }}.conf
      register: nkp_dashboard
      no_log: yes


    - name: desplay nkp dashboard
      debug:
        var: nkp_dashboard.stdout_lines

